import {
  BadgePercent,
  Briefcase,
  Cake,
  Calculator,
  ClipboardList,
  Code,
  Crop,
  EyeOff,
  FileCheck,
  FileCode,
  Type,
  FileImage,
  FileMinus,
  FileOutput,
  FileSpreadsheet,
  FileStack,
  FileText,
  FileType,
  GitCompare,
  Image,
  ImageDown,
  Images,
  KeyRound,
  Landmark,
  ListVideo,
  Languages,
  LayoutGrid,
  ListOrdered,
  ListTodo,
  Lock,
  LockOpen,
  Merge,
  MessageCircle,
  Minimize2,
  PencilLine,
  Ratio,
  Percent,
  Presentation,
  QrCode,
  Receipt,
  RotateCw,
  Scaling,
  ScanLine,
  ScanText,
  ShieldCheck,
  Signature,
  Sparkles,
  Split,
  Stamp,
  TrendingUp,
  Truck,
  Video,
  Wallet,
  Wrench,
  Braces,
  CodeXml,
  Database,
  Link,
  Binary,
  Hash,
  Shuffle,
  Clock,
  CalendarClock,
  Palette,
  Contrast,
  Blend,
  Layers,
  SquareRoundCorner,
  Regex,
  Timer,
  Globe,
  MonitorSmartphone,
  Server,
  Ruler,
  BookOpen,
  ArrowRightLeft,
  Terminal,
  Send,
  Mail,
  Phone,
  Network,
  ScanQrCode,
  Car,
  GraduationCap,
  CalendarRange,
  Coins,
  FerrisWheel,
  Mic,
  PiggyBank,
  House,
  HandCoins,
  ReceiptIndianRupee,
  ChartLine,
  type LucideProps,
} from "lucide-react";
import type { IconName } from "@/lib/tools";

const icons = {
  receipt: Receipt,
  "file-text": FileText,
  "trending-up": TrendingUp,
  truck: Truck,
  wallet: Wallet,
  landmark: Landmark,
  percent: Percent,
  "badge-percent": BadgePercent,
  calculator: Calculator,
  "file-image": FileImage,
  images: Images,
  scaling: Scaling,
  "image-down": ImageDown,
  "list-todo": ListTodo,
  cake: Cake,
  "qr-code": QrCode,
  "key-round": KeyRound,
  "message-circle": MessageCircle,
  briefcase: Briefcase,
  "file-stack": FileStack,
  image: Image,
  "shield-check": ShieldCheck,
  merge: Merge,
  split: Split,
  "file-minus": FileMinus,
  "file-output": FileOutput,
  "layout-grid": LayoutGrid,
  "scan-line": ScanLine,
  minimize: Minimize2,
  wrench: Wrench,
  "scan-text": ScanText,
  "file-type": FileType,
  presentation: Presentation,
  "file-spreadsheet": FileSpreadsheet,
  code: Code,
  "file-check": FileCheck,
  "rotate-cw": RotateCw,
  "list-ordered": ListOrdered,
  stamp: Stamp,
  crop: Crop,
  "pencil-line": PencilLine,
  "clipboard-list": ClipboardList,
  "lock-open": LockOpen,
  lock: Lock,
  signature: Signature,
  "eye-off": EyeOff,
  "git-compare": GitCompare,
  sparkles: Sparkles,
  languages: Languages,
  "file-code": FileCode,
  type: Type,
  video: Video,
  ratio: Ratio,
  "list-video": ListVideo,
  braces: Braces,
  "code-xml": CodeXml,
  database: Database,
  link: Link,
  binary: Binary,
  hash: Hash,
  shuffle: Shuffle,
  clock: Clock,
  "calendar-clock": CalendarClock,
  palette: Palette,
  contrast: Contrast,
  blend: Blend,
  layers: Layers,
  "square-round-corner": SquareRoundCorner,
  regex: Regex,
  timer: Timer,
  globe: Globe,
  "monitor-smartphone": MonitorSmartphone,
  server: Server,
  ruler: Ruler,
  "book-open": BookOpen,
  "arrow-right-left": ArrowRightLeft,
  terminal: Terminal,
  send: Send,
  mail: Mail,
  phone: Phone,
  network: Network,
  "scan-qr-code": ScanQrCode,
  car: Car,
  "graduation-cap": GraduationCap,
  "calendar-range": CalendarRange,
  coins: Coins,
  "ferris-wheel": FerrisWheel,
  mic: Mic,
  "piggy-bank": PiggyBank,
  house: House,
  "hand-coins": HandCoins,
  "receipt-indian-rupee": ReceiptIndianRupee,
  "chart-line": ChartLine,
} satisfies Record<IconName, React.ComponentType<LucideProps>>;

export function ToolIcon({ name, ...props }: { name: IconName } & LucideProps) {
  const Icon = icons[name];
  return <Icon aria-hidden {...props} />;
}
