"use client";

import { useState } from "react";
import { z } from "zod";
import { calculateDueDate, calculateMacros, calculateOneRepMax, calculateTdee, type ActivityLevel, type EquationSex, type FitnessGoal } from "@/lib/calculations/health";
import { formatNumber } from "@/lib/format";
import { numberString, validateInputs } from "@/lib/validation/fields";
import { DateField, NumberField, SegmentedControl, SelectField } from "@/components/shared/form-fields";
import { CopyButton, ResetButton } from "@/components/shared/result-actions";
import { CalculatorLayout, EmptyResult, InputCard, ResultCard, ResultRows } from "@/components/shared/result-card";

const tdeeSchema = z.object({ age: numberString({ min: 18, max: 100, integer: true }), weight: numberString({ min: 25, max: 400 }), height: numberString({ min: 100, max: 250 }) });
const TDEE_DEFAULTS = { age: "", weight: "", height: "" };
const activities = [{ value: "sedentary", label: "Sedentary — little structured exercise" }, { value: "light", label: "Light — exercise 1–3 days/week" }, { value: "moderate", label: "Moderate — exercise 3–5 days/week" }, { value: "active", label: "Active — hard exercise 6–7 days/week" }, { value: "very-active", label: "Very active — intense training or physical work" }] as const;

export function TdeeCalculator() {
  const [values, setValues] = useState(TDEE_DEFAULTS); const [sex, setSex] = useState<EquationSex>("female"); const [activity, setActivity] = useState<ActivityLevel>("moderate");
  const validation = validateInputs(tdeeSchema, values); const result = validation.ok ? calculateTdee({ sex, age: validation.data.age, weightKg: validation.data.weight, heightCm: validation.data.height, activity }) : null;
  const set = (key: keyof typeof values) => (value: string) => setValues((current) => ({ ...current, [key]: value }));
  return <CalculatorLayout inputs={<InputCard><SegmentedControl label="Sex used by the Mifflin-St Jeor equation" value={sex} onChange={setSex} options={[{ value: "female", label: "Female" }, { value: "male", label: "Male" }]} /><div className="grid gap-4 sm:grid-cols-3"><NumberField label="Age" suffix="years" value={values.age} onChange={set("age")} error={validation.errors.age} /><NumberField label="Weight" suffix="kg" value={values.weight} onChange={set("weight")} error={validation.errors.weight} /><NumberField label="Height" suffix="cm" value={values.height} onChange={set("height")} error={validation.errors.height} /></div><SelectField label="Activity level" value={activity} onChange={setActivity} options={activities} /></InputCard>} result={result ? <ResultCard highlightLabel="Estimated TDEE" highlightValue={`${formatNumber(result.tdee)} kcal/day`} highlightCaption="Estimated maintenance energy, not a measured value" actions={<><CopyButton text={`Estimated TDEE: ${result.tdee} kcal/day. Estimated resting energy: ${result.bmr} kcal/day.`} /><ResetButton onReset={() => setValues(TDEE_DEFAULTS)} /></>}><ResultRows rows={[{ label: "Estimated resting energy (BMR)", value: `${formatNumber(result.bmr)} kcal/day` }, { label: "Activity multiplier", value: `${result.factor}×` }, { label: "Estimated weekly maintenance", value: `${formatNumber(result.tdee * 7)} kcal`, emphasis: true }]} /></ResultCard> : <EmptyResult message="Enter adult age, weight and height to estimate resting and total daily energy expenditure." />} />;
}

const macroSchema = z.object({ tdee: numberString({ min: 800, max: 10000 }) });
export function MacronutrientCalculator() {
  const [tdee, setTdee] = useState(""); const [goal, setGoal] = useState<FitnessGoal>("maintain"); const validation = validateInputs(macroSchema, { tdee }); const result = validation.ok ? calculateMacros(validation.data.tdee, goal) : null;
  return <CalculatorLayout inputs={<InputCard><NumberField label="Estimated maintenance calories (TDEE)" suffix="kcal/day" value={tdee} onChange={setTdee} error={validation.errors.tdee} hint="Use the TDEE Calculator if you do not know this value." /><SegmentedControl label="Goal" value={goal} onChange={setGoal} options={[{ value: "lose", label: "Gradual loss" }, { value: "maintain", label: "Maintain" }, { value: "gain", label: "Gradual gain" }]} /><p className="text-xs leading-relaxed text-muted-foreground">This planning split uses 45% carbohydrate, 25% protein and 30% fat. Individual needs can differ.</p></InputCard>} result={result ? <ResultCard highlightLabel="Daily calorie target" highlightValue={`${formatNumber(result.calories)} kcal`} highlightCaption="General planning estimate for adults" actions={<><CopyButton text={`Daily target: ${result.calories} kcal, ${result.proteinGrams} g protein, ${result.carbGrams} g carbohydrate, ${result.fatGrams} g fat.`} /><ResetButton onReset={() => setTdee("")} /></>}><ResultRows rows={[{ label: "Protein (25%)", value: `${result.proteinGrams} g` }, { label: "Carbohydrate (45%)", value: `${result.carbGrams} g` }, { label: "Fat (30%)", value: `${result.fatGrams} g` }]} /></ResultCard> : <EmptyResult message="Enter estimated maintenance calories and choose a goal to calculate a balanced macro starting point." />} />;
}

const dateFormatter = new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" });
function addDays(date: Date, days: number) { return new Date(date.getTime() + days * 86_400_000); }
export function PregnancyDueDateCalculator() {
  const [lmp, setLmp] = useState(""); const [cycle, setCycle] = useState("28"); const cycleNumber = Number(cycle); const valid = /^\d{4}-\d{2}-\d{2}$/.test(lmp) && Number.isFinite(cycleNumber) && cycleNumber >= 20 && cycleNumber <= 45;
  const start = valid ? new Date(`${lmp}T00:00:00`) : null; const result = start ? calculateDueDate(start, cycleNumber) : null;
  return <CalculatorLayout inputs={<InputCard><DateField label="First day of last menstrual period (LMP)" value={lmp} onChange={setLmp} max={new Date().toISOString().slice(0, 10)} /><NumberField label="Average cycle length" suffix="days" value={cycle} onChange={setCycle} hint="Use 28 days if unsure; cycle variation affects the estimate." /></InputCard>} result={result && start ? <ResultCard highlightLabel="Estimated due date" highlightValue={dateFormatter.format(result.dueDate)} highlightCaption="Clinical dating may change after ultrasound" actions={<><CopyButton text={`Estimated due date: ${dateFormatter.format(result.dueDate)}.`} /><ResetButton onReset={() => { setLmp(""); setCycle("28"); }} /></>}><ResultRows rows={[{ label: "Estimated conception date", value: dateFormatter.format(result.conceptionDate) }, { label: "End of first trimester (13w 6d)", value: dateFormatter.format(addDays(start, 97)) }, { label: "Start of third trimester (28w)", value: dateFormatter.format(addDays(start, 196)) }]} /></ResultCard> : <EmptyResult message="Enter the first day of the last menstrual period to estimate the due date." />} />;
}

const maxSchema = z.object({ weight: numberString({ min: 1, max: 1000 }), reps: numberString({ min: 1, max: 12, integer: true }) });
export function OneRepMaxCalculator() {
  const [values, setValues] = useState({ weight: "", reps: "5" }); const validation = validateInputs(maxSchema, values); const result = validation.ok ? calculateOneRepMax(validation.data.weight, validation.data.reps) : null;
  return <CalculatorLayout inputs={<InputCard><NumberField label="Weight lifted" suffix="kg" value={values.weight} onChange={(weight) => setValues((v) => ({ ...v, weight }))} error={validation.errors.weight} /><NumberField label="Completed repetitions" suffix="reps" value={values.reps} onChange={(reps) => setValues((v) => ({ ...v, reps }))} error={validation.errors.reps} hint="Use a challenging set of 1–12 controlled repetitions." /></InputCard>} result={result ? <ResultCard highlightLabel="Estimated one-rep max" highlightValue={`${formatNumber(result.estimate)} kg`} highlightCaption="Average of Epley and Brzycki estimates" actions={<><CopyButton text={`Estimated 1RM: ${formatNumber(result.estimate)} kg from ${values.weight} kg × ${values.reps} reps.`} /><ResetButton onReset={() => setValues({ weight: "", reps: "5" })} /></>}><ResultRows rows={[{ label: "Epley estimate", value: `${formatNumber(result.epley)} kg` }, { label: "Brzycki estimate", value: `${formatNumber(result.brzycki)} kg` }, ...result.percentages.map((item) => ({ label: `${item.percent}% training weight`, value: `${formatNumber(item.weight)} kg` }))]} /></ResultCard> : <EmptyResult message="Enter a completed lift set to estimate your one-repetition maximum and training weights." />} />;
}
